### ISSUE TITLE
RedisInsight with ingress-nginx giving error on actions

### ISSUE THREAD

**Issue by fahadahammed** [redis-stack/redis-stack-docs#129]
I have been trying to deploy redisinsight in EKS with ingress-nginx. I do get the "EULA and Privacy Settings" screen when I access but trying to confirm gives me the proxy error.

```
Are you behind a proxy? If so, please set the RedisInsight environment variables.
```
I tried to pass the environment variable:

```yaml
        env:
          - name: RITRUSTEDORIGINS
            value: "https://<domain-that-is-configured-for-ingress>,https://<ELB-ID>.elb.us-west-1.amazonaws.com"
```

But still no luck. I this workable with ingress-nginx?
