### ISSUE TITLE
Redis Stack

### ISSUE THREAD

**Issue by carlosmgv02** [redis-stack/redis-stack-docs#179]
Hello, is there any way of starting a docker container which uses the redis-stack image and set a securtity password?

**Comment by vic-951** [comment]
Yes you can do it with docker compose and a configuration file. In the configuration file you can put your password

```
version: '3'

services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    container_name: rds
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
    volumes:
      - /home/user/docker/redis/data:/data
      - /home/user/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
```
